CodigoCiudadano\DenunciaBundle\Entity\Localidad:
    type: entity
    table: localidad
    indexes:
        IDX_4F68E0104E7121AF:
            columns:
                - provincia_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
        slug:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
        coordenadas:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
    manyToOne:
        provincia:
            targetEntity: Provincia
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                provincia_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
