CodigoCiudadano\DenunciaBundle\Entity\Provincia:
    type: entity
    table: provincia
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
        slug:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
        coordenadas:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
