CodigoCiudadano\DenunciaBundle\Entity\TipoDenuncia:
    type: entity
    table: tipo_denuncia
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tipo:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        slug:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        publicado:
            type: boolean
            nullable: false
            comment: ''
    lifecycleCallbacks: {  }
