CodigoCiudadano\DenunciaBundle\Entity\VideoYoutube:
    type: entity
    table: video_youtube
    indexes:
        IDX_1595709917048D94:
            columns:
                - denuncia_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        url:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
    manyToOne:
        denuncia:
            targetEntity: Denuncia
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                denuncia_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
