parameters:
#    codigo_ciudadano_Denuncia.example.class: CodigoCiudadano\DenunciaBundle\Example

services:
#    codigo_ciudadano_Denuncia.example:
#        class: %codigo_ciudadano_Denuncia.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
